var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/route.js")
R.c("server/chunks/[root-of-the-server]__0l7eyxr._.js")
R.c("server/chunks/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_1q51sxr._.js")
R.c("server/chunks/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_src_lib_0lf9gql._.js")
R.c("server/chunks/[root-of-the-server]__0fm40r_._.js")
R.c("server/chunks/[root-of-the-server]__1o04vg3._.js")
R.c("server/chunks/006f_172d_-k._.js")
R.c("server/chunks/1lgo_scratch_agente-bora-chat_viral-studio-ai_src_lib_pipeline_index_ts_0ge5e_d._.js")
R.c("server/chunks/1nax_viral-studio-ai__next-internal_server_app_api_projects_route_actions_136cm39.js")
R.m(45641)
module.exports=R.m(45641).exports
