var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[id]/ai-edit/route.js")
R.c("server/chunks/[root-of-the-server]__09pr0f9._.js")
R.c("server/chunks/006f_next_dist_esm_build_templates_app-route_1isbjvq.js")
R.c("server/chunks/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_src_lib_1aw1e15._.js")
R.c("server/chunks/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_1q51sxr._.js")
R.c("server/chunks/006f_172d_-k._.js")
R.c("server/chunks/[root-of-the-server]__1o04vg3._.js")
R.c("server/chunks/[root-of-the-server]__0fm40r_._.js")
R.c("server/chunks/1lns__next-internal_server_app_api_projects_[id]_ai-edit_route_actions_1h7jgj8.js")
R.m(14838)
module.exports=R.m(14838).exports
