var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/reset/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eo8l1c._.js")
R.c("server/chunks/ssr/006f_next_dist_1imgbxt._.js")
R.c("server/chunks/ssr/006f_next_dist_esm_build_templates_app-page_1b0w8_g.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jbj2il._.js")
R.c("server/chunks/ssr/006f_next_dist_0oisovq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01jvqep._.js")
R.c("server/chunks/ssr/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_0n9bzac._.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_1jlbiec._.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_forbidden_0n48hkv.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_unauthorized_05dupvw.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_global-error_1v8elrx.js")
R.c("server/chunks/ssr/1nax_viral-studio-ai__next-internal_server_app_reset_page_actions_0qh-du1.js")
R.m(76906)
module.exports=R.m(76906).exports
