var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1m6w_3f._.js")
R.c("server/chunks/ssr/006f_next_dist_1imgbxt._.js")
R.c("server/chunks/ssr/006f_next_dist_esm_build_templates_app-page_1keahcd.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jbj2il._.js")
R.c("server/chunks/ssr/006f_next_dist_0oisovq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01jvqep._.js")
R.c("server/chunks/ssr/_gemini_antigravity-ide_scratch_agente-bora-chat_viral-studio-ai_0n9bzac._.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_1jlbiec._.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_forbidden_0n48hkv.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_unauthorized_05dupvw.js")
R.c("server/chunks/ssr/006f_next_dist_client_components_builtin_global-error_1v8elrx.js")
R.c("server/chunks/ssr/0_9z_agente-bora-chat_viral-studio-ai__next-internal_server_app_page_actions_1nmout0.js")
R.m(55520)
module.exports=R.m(55520).exports
